name: datafusion
description: A new Flutter application.
version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  linalg: ^0.3.2
  fast_noise: ^0.1.3+1
  rxdart: ^0.24.0
  animations: ^1.0.0+5
  flutter_svg: ^0.17.4
  shared_preferences: ^0.5.7+1
  after_layout: ^1.0.7+2
  shimmer: ^1.1.1
  syncfusion_flutter_charts: ^18.1.46
  syncfusion_flutter_core: ^18.1.46
  get_version: ^0.2.2
  native_pdf_view: ^3.2.0-dev.1
  open_file: ^3.0.1
  path_provider: ^1.6.7
  flutter_markdown: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/nunito_semibold.ttf
    - assets/fonts/vazir_light.ttf
    - assets/fonts/vazir_thin.ttf
    - assets/icon/icon.png
    - assets/icons/cube.svg
    - assets/icons/filter_off.svg
    - assets/icons/filter_on.svg
    - assets/icons/merge.svg
    - assets/icons/sensor.svg
    - assets/images/data_fusion_img.png
    - assets/images/kalman_filter_img.png
    - assets/images/merge_sensor_img.png
    - assets/images/virtual_object_img.png
    - assets/images/virtual_sensor_img.jpg
    - assets/info/data_fusion.md
    - assets/info/kalman_filter.md
    - assets/info/merge_sensor.md
    - assets/info/report.pdf
    - assets/info/virtual_object.md
    - assets/info/virtual_sensor.md
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir_thin.ttf
          weight: 200
        - asset: assets/fonts/vazir_light.ttf
          weight: 300
    - family: Nutino
      fonts:
        - asset: assets/fonts/nunito_semibold.ttf
          weight: 500

