/// Generated by AssetsRefGenerator on 2020/05/06
class Res {
  static const String nunito_semibold = "assets/fonts/nunito_semibold.ttf";
  static const String vazir_light = "assets/fonts/vazir_light.ttf";
  static const String vazir_thin = "assets/fonts/vazir_thin.ttf";
  static const String icon = "assets/icon/icon.png";
  static const String cube = "assets/icons/cube.svg";
  static const String filter_off = "assets/icons/filter_off.svg";
  static const String filter_on = "assets/icons/filter_on.svg";
  static const String merge = "assets/icons/merge.svg";
  static const String sensor = "assets/icons/sensor.svg";
}
