/// Generated by AssetsRefGenerator on 2020/05/07
class Res {
  static const String nunito_semibold = "assets/fonts/nunito_semibold.ttf";
  static const String vazir_light = "assets/fonts/vazir_light.ttf";
  static const String vazir_thin = "assets/fonts/vazir_thin.ttf";
  static const String icon = "assets/icon/icon.png";
  static const String cube = "assets/icons/cube.svg";
  static const String filter_off = "assets/icons/filter_off.svg";
  static const String filter_on = "assets/icons/filter_on.svg";
  static const String merge = "assets/icons/merge.svg";
  static const String sensor = "assets/icons/sensor.svg";
  static const String data_fusion_img = "assets/images/data_fusion_img.png";
  static const String kalman_filter_img = "assets/images/kalman_filter_img.png";
  static const String merge_sensor_img = "assets/images/merge_sensor_img.png";
  static const String virtual_object_img = "assets/images/virtual_object_img.png";
  static const String virtual_sensor_img = "assets/images/virtual_sensor_img.jpg";
  static const String data_fusion = "assets/info/data_fusion.md";
  static const String kalman_filter = "assets/info/kalman_filter.md";
  static const String merge_sensor = "assets/info/merge_sensor.md";
  static const String report = "assets/info/report.pdf";
  static const String virtual_object = "assets/info/virtual_object.md";
  static const String virtual_sensor = "assets/info/virtual_sensor.md";
}
